# name: Deploy to GitHub Pages

# on:
#   push:
#     branches:
#       - master
#       - main

# jobs:
#   build-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: Setup Node
#         uses: actions/setup-node@v1
#         with:
#           node-version: '12.x'

#       - run: yarn

#       - run: yarn build

#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./build



# name: Trigger Netlify Build

# on:
#   schedule:
#     # You can use https://crontab.guru to generate the
#     # desired cron sheduled :)
#     - cron: "0 10 * * 1" # At 10:00 on Monday.

# jobs:
#   build:
#     name: Request Netlify Webhook
#     runs-on: ubuntu-latest
#     steps:
#       - name: Ping
#         run: curl -X POST -d {} https://api.netlify.com/build_hooks/601b6158a8a0276cdf660e5a


